version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - '5601:5601'
    restart: on-failure
  frontend:
    build:
      context: ./frontend
    ports:
      - '5000:5000'
    restart: on-failure